### ISSUE TITLE
Implement tokenizer

### ISSUE THREAD

**Issue by iqltd** [micul01/javashcript#15]
Separate the input into lists of tokens (words separated by metacharacters)

**Comment by iqltd** [comment]
From the spec:
"metacharacter
A character that, when unquoted, separates words. A metacharacter is a space,
tab, newline, or one of the following characters: ‘|’, ‘&’, ‘;’, ‘(’, ‘)’, ‘<’, or ‘>’."

**Comment by micul01** [comment]
Drop the unquoted escape characters and "\newline"
